### ISSUE TITLE
!DOCTYPE html tag in result

### ISSUE THREAD

**Issue by LeMoussel** [grokify/html-strip-tags-go#1]
With this site http://cocon.se/,  I have `<!DOCTYPE html>` in result text content.
Is it normal?

**Test**
```
	originalTest := "<!DOCTYPE html><h1>Hello World</h1>"
	strippedTest := strip.StripTags(originalTest) // => "<!DOCTYPE html>Hello WorldHello World"
	println(strippedTest)
```

**Comment by grokify** [comment]
This is normal and expected for an HTML page such as the one you linked to. `DOCTYPE` is a preamble that is required for HTML 5 and also technically not a HTML tag. This is required to tell the browser how to interpret your page (e.g. what version of HTML) and to prevent it from using quirks mode.

Here's some info on this:

https://www.w3.org/TR/html5/syntax.html#syntax-doctype

> A DOCTYPE is a required preamble.
> NOTE: DOCTYPEs are required for legacy reasons. When omitted, browsers tend to use a different rendering mode that is incompatible with some specifications. Including the DOCTYPE in a document ensures that the browser makes a best-effort attempt at following the relevant specifications.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Introduction_to_HTML5

> The doctype for HTML5 is very simple. To indicate that your HTML content uses HTML5, simply use:
> `<!DOCTYPE html>`
> Doing so will cause even browsers that don't presently support HTML5 to enter into standards mode, which means that they'll interpret the long-established parts of HTML in an HTML5-compliant way while ignoring the new features of HTML5 they don't support.

https://stackoverflow.com/questions/414891/what-is-doctype

> Basically, the DOCTYPE describes the HTML that will be used in your page.
> Browsers also use the DOCTYPE to determine how to render a page. Not including a DOCTYPE or including an incorrect DOCTYPE can trigger quirks mode.

https://www.w3schools.com/tags/tag_doctype.asp

> The <!DOCTYPE> declaration is not an HTML tag; it is an instruction to the web browser about what version of HTML the page is written in.

https://stackoverflow.com/questions/18373091/what-happens-when-i-remove-doctype-in-html

> Without a Doctype:
> 1. Browsers enter Quirks mode and try to deal with your code as if it was written in the late 90s. This means they emulate many bugs that existed in their predecessors. They aren't particularly consistent about how they do this (so you'll get significantly different results in, for example, Firefox and Internet Explorer).
> 2. You will add a validation error to your markup
> 3. Validation tools won't be able to tell what specification to validate against unless you tell them though some other method

I'm closing this now with the link you mentioned. If you have other questions, please feel free to continue the discussion here.
